USE dbproject;

CREATE SCHEMA IF NOT EXISTS dbproject;

CREATE TABLE IF NOT EXISTS MEDICATION (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROBAND (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    gender_id BIGINT NOT NULL,
    birthday DATE NOT NULL,
    weight DOUBLE(8, 2) NOT NULL,
    height DOUBLE(8, 2) NOT NULL,
    health FLOAT,
    country_id BIGINT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    bmi DOUBLE(8, 2) AS (weight / (height/100 * height/100)),
    last_changed TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS update_last_changed BEFORE UPDATE ON PROBAND FOR EACH ROW SET NEW.last_changed = CURRENT_TIMESTAMP;

DELIMITER ;

CREATE TABLE IF NOT EXISTS PROBANDMEDICATION (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    proband_id BIGINT NOT NULL,
    medication_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS DISEASES (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS COUNTRY (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    countrycode varchar(3) NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROBANDDISEASES(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    proband_id BIGINT NOT NULL,
    sickness_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS GENDER(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name varchar(50)
);


ALTER TABLE PROBANDMEDICATION
    -- ADD CONSTRAINT `patientmedication_proband_id_fk`
        ADD FOREIGN KEY (`proband_id`) REFERENCES PROBAND(`id`);

ALTER TABLE
    PROBANDDISEASES
    -- ADD CONSTRAINT `patientsickness_patientid_fk`
        ADD FOREIGN KEY (`proband_id`) REFERENCES PROBAND(`id`);
ALTER TABLE
    PROBANDMEDICATION
    -- ADD CONSTRAINT `patientmedication_medicationid_fk`
        ADD FOREIGN KEY(`medication_id`) REFERENCES `MEDICATION`(`id`);
ALTER TABLE
    PROBAND
    -- ADD CONSTRAINT `patient_countryid_fk`
        ADD FOREIGN KEY (`country_id`) REFERENCES `COUNTRY`(`id`);
ALTER TABLE
    PROBAND
    -- ADD CONSTRAINT `patient_countryid_fk`
        ADD FOREIGN KEY (`gender_id`) REFERENCES `GENDER`(`id`);
ALTER TABLE
    PROBANDDISEASES
    -- ADD CONSTRAINT `patientsickness_sicknessid_fk_2`
        ADD FOREIGN KEY (`sickness_id`) REFERENCES `DISEASES`(`id`);

SET GLOBAL FOREIGN_KEY_CHECKS=0;